


// type EmailCardProps = {
//   summary: string
//   confidence?: number
//   subject?: string
//   sender?: string
//   has_attachment?: boolean
// }

// export function EmailCard({ summary,confidence,subject,sender,has_attachment }: EmailCardProps) {
//   return (
//     <div className="p-4 rounded-xl border border-zinc-200 dark:border-zinc-700 bg-white dark:bg-zinc-900 shadow-sm transition hover:shadow-md">
//       {/* Fake subject (for now) */}
//       {/* <div className="text-sm font-semibold mb-1">
//         Email Summary
//       </div> */}

//       <div className="mb-1">
//   <div className="text-sm font-semibold text-zinc-900 dark:text-zinc-100">
//     {subject ? subject : "Email Summary"}
//   </div>
//   {sender && (
//     <div className="text-xs text-pink-500 dark:text-pink-400 mt-0.5">
//       {sender}
//     </div>
//   )}
//     {has_attachment && (
//     <div className="text-xs text-blue-500 mt-1">
//       📎 Has Attachment
//     </div>
//   )}
  
// </div>
//       {/* Summary text */}
//       <p className="text-sm text-zinc-700 dark:text-zinc-300 leading-relaxed line-clamp-4 mt-2">
//         {summary}
//       </p>


//       {/* Optional footer
//       <div className="mt-3 text-xs font-medium text-blue-600 dark:text-blue-400">
//         Generated by Nemo
//       </div> */}
      
    

//       {/* {confidence !== undefined && (
//   <div className="mt-2 inline-flex items-center rounded-full bg-blue-50 px-3 py-1 text-xs font-semibold text-blue-700 dark:bg-blue-900/40 dark:text-blue-300">
//     Confidence: {Math.round(confidence * 100)}%
//   </div> */}
// {/* 
// )} */}
// <div className="mt-3 flex items-center justify-between text-xs">
//         <span className="text-blue-600 dark:text-blue-400 font-medium">
//           Generated by Nemo
//         </span>

//         {confidence !== undefined && (
//           <span className="px-2 py-1 rounded-full bg-blue-100 dark:bg-blue-900/40 text-blue-700 dark:text-blue-300 font-semibold">
//             {Math.round(confidence * 100)}% confidence
//           </span>
//         )}
//       </div>



//     </div>
//   )
// }


type EmailCardProps = {
  summary: string
  confidence?: number
  subject?: string
  sender?: string
  has_attachment?: boolean
}

export function EmailCard({ summary, confidence, subject, sender, has_attachment }: EmailCardProps) {
  return (
    <div className="p-4 rounded-xl border border-zinc-200 dark:border-zinc-700 
                    bg-white dark:bg-zinc-900 shadow-sm transition 
                    hover:shadow-md hover:border-zinc-300 dark:hover:border-zinc-600">

      {/* SUBJECT + SENDER */}
      <div className="mb-2">
        <div className="text-sm font-semibold text-zinc-900 dark:text-zinc-100">
          {subject || "Email Summary"}
        </div>

        {sender && (
          <div className="text-xs text-pink-500 dark:text-pink-400 mt-0.5">
            {sender}
          </div>
        )}

        {has_attachment && (
          <div className="text-xs mt-1 inline-flex items-center gap-1 text-blue-600 dark:text-blue-400">
            📎 <span className="font-medium">Attachment</span>
          </div>
        )}
      </div>

      {/* SUMMARY */}
      <p className="text-sm text-zinc-700 dark:text-zinc-300 leading-relaxed mt-1 line-clamp-4">
        {summary}
      </p>

      {/* FOOTER */}
      <div className="mt-3 flex items-center justify-between text-xs">
        
        <span className="text-blue-600 dark:text-blue-400 font-medium">
          Generated by Nemo
        </span>

        {confidence !== undefined && (
          <span className="px-2 py-1 rounded-full bg-blue-100 dark:bg-blue-900/30 
                          text-blue-700 dark:text-blue-300 font-semibold shadow-sm">
            {Math.round(confidence * 100)}% confidence
          </span>
        )}
      </div>

    </div>
  )
}