


type EmailCardProps = {
  summary: string
  confidence?: number
  subject?: string
  sender?: string
  has_attachment?: boolean
}

export function EmailCard({ summary,confidence,subject,sender,has_attachment }: EmailCardProps) {
  return (
    <div className="p-4 rounded-lg border border-zinc-200 dark:border-zinc-700 bg-white dark:bg-zinc-900">
      {/* Fake subject (for now) */}
      {/* <div className="text-sm font-semibold mb-1">
        Email Summary
      </div> */}

      <div className="mb-1">
  <div className="text-sm font-semibold">
    {subject ? subject : "Email Summary"}
  </div>
  {sender && (
    <div className="text-xs text-pink-500 dark:text-pink-400">
      {sender}
    </div>
  )}
    {has_attachment && (
    <div className="text-xs text-blue-500 mt-1">
      📎 Has Attachment
    </div>
  )}
  
</div>
      {/* Summary text */}
      <p className="text-sm text-zinc-700 dark:text-zinc-300 leading-relaxed line-clamp-4">
        {summary}
      </p>


      {/* Optional footer */}
      <div className="mt-2 text-xs font-medium text-blue-600 dark:text-blue-400">
        Generated by Nemo
      </div>
    

      {confidence !== undefined && (
  <div className="text-xs font-medium text-orange-600 dark:text-orange-400 mt-1">
    Confidence: {Math.round(confidence * 100)}%
  </div>

)}

    </div>
  )
}